// resources/js/Pages/Auth/Register.tsx
import React, { ChangeEvent, FormEvent, useEffect } from 'react';
import { Head, Link, useForm } from '@inertiajs/inertia-react';
import { GuestLayout } from '@/Layouts/GuestLayout';
import { JetButton, JetValidationErrors } from '@/Components/Jetstream';
import route from '@/lib/route';
import { AuthLabel } from '@/Components/Auth/Label';
import { AuthInput } from '@/Components/Auth/Input';

export default function Register() {
  const { data, setData, post, processing, errors, reset } = useForm({
    name: '',
    email: '',
    password: '',
    password_confirmation: '',
  });

  useEffect(() => {
    return () => {
      reset('password', 'password_confirmation');
    };
  }, []);

  const onHandleChange = (event: ChangeEvent<HTMLInputElement>) => {
    const name = event.target.name as 'name' | 'email' | 'password' | 'password_confirmation';
    setData(name, event.target.value);
  };

  const submit = (e: FormEvent) => {
    e.preventDefault();

    post(route('register'));
  };

  return (
    <GuestLayout>
      <Head title="Register" />

      <JetValidationErrors errors={errors} />

      <form onSubmit={submit}>
        <div>
          <AuthLabel title="Name" name="name" />
          <AuthInput
            type="text"
            name="name"
            value={data.name}
            className="mt-1 block w-full"
            autoComplete="name"
            autoFocus
            onChange={e => setData('name', e.target.value)}
            required
          />
        </div>

        <div className="mt-4">
          <AuthLabel title="Email" name="email" />

          <AuthInput
            type="email"
            name="email"
            value={data.email}
            className="mt-1 block w-full"
            autoComplete="username"
            onChange={onHandleChange}
            required
          />
        </div>

        <div className="mt-4">
          <AuthLabel title="Password" name="password" />
          <AuthInput
            type="password"
            name="password"
            value={data.password}
            className="mt-1 block w-full"
            autoComplete="new-password"
            onChange={onHandleChange}
            required
          />
        </div>

        <div className="mt-4">
          <AuthLabel title="Confirm Password" name="password_confirmation" />
          <AuthInput
            type="password"
            name="password_confirmation"
            value={data.password_confirmation}
            className="mt-1 block w-full"
            onChange={onHandleChange}
            required
          />
        </div>

        <div className="flex items-center justify-end mt-4">
          <Link href={route('login')} className="underline text-sm text-gray-600 hover:text-gray-900">
            Already registered?
          </Link>

          <JetButton className="ml-4" processing={processing}>
            Register
          </JetButton>
        </div>
      </form>
    </GuestLayout>
  );
}

// resources/Jetstream/Pages/Register.vue
<template>
    <Head title="Register" />

    <jet-authentication-card>
        <template #logo>
            <jet-authentication-card-logo />
        </template>

        <jet-validation-errors class="mb-4" />

        <form @submit.prevent="submit">
            <div>
                <jet-label for="name" value="Name" />
                <jet-input id="name" type="text" class="mt-1 block w-full" v-model="form.name" required autofocus autocomplete="name" />
            </div>

            <div class="mt-4">
                <jet-label for="email" value="Email" />
                <jet-input id="email" type="email" class="mt-1 block w-full" v-model="form.email" required />
            </div>

            <div class="mt-4">
                <jet-label for="password" value="Password" />
                <jet-input id="password" type="password" class="mt-1 block w-full" v-model="form.password" required autocomplete="new-password" />
            </div>

            <div class="mt-4">
                <jet-label for="password_confirmation" value="Confirm Password" />
                <jet-input id="password_confirmation" type="password" class="mt-1 block w-full" v-model="form.password_confirmation" required autocomplete="new-password" />
            </div>

            <div class="mt-4" v-if="$page.props.jetstream.hasTermsAndPrivacyPolicyFeature">
                <jet-label for="terms">
                    <div class="flex items-center">
                        <jet-checkbox name="terms" id="terms" v-model:checked="form.terms" />

                        <div class="ml-2">
                            I agree to the <a target="_blank" :href="route('terms.show')" class="underline text-sm text-gray-600 hover:text-gray-900">Terms of Service</a> and <a target="_blank" :href="route('policy.show')" class="underline text-sm text-gray-600 hover:text-gray-900">Privacy Policy</a>
                        </div>
                    </div>
                </jet-label>
            </div>

            <div class="flex items-center justify-end mt-4">
                <Link :href="route('login')" class="underline text-sm text-gray-600 hover:text-gray-900">
                    Already registered?
                </Link>

                <jet-button class="ml-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Register
                </jet-button>
            </div>
        </form>
    </jet-authentication-card>
</template>

<script>
    import { defineComponent } from 'vue'
    import JetAuthenticationCard from '@/../../../Jetstream/AuthenticationCard.vue'
    import JetAuthenticationCardLogo from '@/../../../Jetstream/AuthenticationCardLogo.vue'
    import JetButton from '@/../../../Jetstream/Button.vue'
    import JetInput from '@/../../../Jetstream/Input.vue'
    import JetCheckbox from '@/../../../Jetstream/Checkbox.vue'
    import JetLabel from '@/../../../Jetstream/Label.vue'
    import JetValidationErrors from '@/../../../Jetstream/ValidationErrors.vue'
    import { Head, Link } from '@inertiajs/inertia-vue3';

    export default defineComponent({
        components: {
            Head,
            JetAuthenticationCard,
            JetAuthenticationCardLogo,
            JetButton,
            JetInput,
            JetCheckbox,
            JetLabel,
            JetValidationErrors,
            Link,
        },

        data() {
            return {
                form: this.$inertia.form({
                    name: '',
                    email: '',
                    password: '',
                    password_confirmation: '',
                    terms: false,
                })
            }
        },

        methods: {
            submit() {
                this.form.post(this.route('register'), {
                    onFinish: () => this.form.reset('password', 'password_confirmation'),
                })
            }
        }
    })
</script>
