// resources/js/Pages/Auth/ResetPassword.tsx
import * as React from 'react';
import { FormEvent } from 'react';
import { Head, useForm } from '@inertiajs/inertia-react';

import useRoute from '@/Hooks/useRoute';
import { GuestLayout } from '@/Layouts/GuestLayout';
import { JetButton } from '@/Components/Jetstream/Button';
import { AuthLabel } from '@/Components/Auth/Label';
import { AuthInput } from '@/Components/Auth/Input';

interface Props {
  token: string;
  email: string;
}

export default function ResetPassword({ token, email }: Props) {
  const route = useRoute();
  const form = useForm({
    token,
    email,
    password: '',
    password_confirmation: '',
  });

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    form.post(route('password.update'), {
      onFinish: () => form.reset('password', 'password_confirmation'),
    });
  };

  return (
    <GuestLayout>
      <Head title="Reset Password" />

      <form onSubmit={onSubmit}>
        <div className="mt-4">
          <AuthLabel title="Email" name="email" error={form.errors.email} />
          <AuthInput
            type="email"
            name="email"
            value={form.data.email}
            className="mt-1 block w-full"
            autoComplete="username"
            onChange={e => form.setData('email', e.target.value)}
            required
            hasError={!!form.errors.email}
          />
        </div>

        <div className="mt-4">
          <AuthLabel title="Password" name="password" error={form.errors.password} />
          <AuthInput
            type="password"
            name="password"
            value={form.data.password}
            className="mt-1 block w-full"
            autoComplete="new-password"
            onChange={e => form.setData('password', e.target.value)}
            required
            hasError={!!form.errors.password}
          />
        </div>

        <div className="mt-4">
          <AuthLabel title="Confirm Password" name="password_confirmation" error={form.errors.password_confirmation} />
          <AuthInput
            type="password"
            name="password_confirmation"
            value={form.data.password_confirmation}
            className="mt-1 block w-full"
            onChange={e => form.setData('password_confirmation', e.target.value)}
            required
            hasError={!!form.errors.password_confirmation}
          />
        </div>

        <div className="flex items-center justify-end mt-4">
          <JetButton processing={form.processing}>
            Reset Password
          </JetButton>
        </div>
      </form>
    </GuestLayout>
  );
}

// resources/Jetstream/Pages/ResetPassword.vue
<template>
    <Head title="Reset Password" />

    <jet-authentication-card>
        <template #logo>
            <jet-authentication-card-logo />
        </template>

        <jet-validation-errors class="mb-4" />

        <form @submit.prevent="submit">
            <div>
                <jet-label for="email" value="Email" />
                <jet-input id="email" type="email" class="mt-1 block w-full" v-model="form.email" required autofocus />
            </div>

            <div class="mt-4">
                <jet-label for="password" value="Password" />
                <jet-input id="password" type="password" class="mt-1 block w-full" v-model="form.password" required autocomplete="new-password" />
            </div>

            <div class="mt-4">
                <jet-label for="password_confirmation" value="Confirm Password" />
                <jet-input id="password_confirmation" type="password" class="mt-1 block w-full" v-model="form.password_confirmation" required autocomplete="new-password" />
            </div>

            <div class="flex items-center justify-end mt-4">
                <jet-button :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Reset Password
                </jet-button>
            </div>
        </form>
    </jet-authentication-card>
</template>

<script>
    import { defineComponent } from 'vue';
    import { Head } from '@inertiajs/inertia-vue3';
    import JetAuthenticationCard from '@/../../../Jetstream/AuthenticationCard.vue'
    import JetAuthenticationCardLogo from '@/../../../Jetstream/AuthenticationCardLogo.vue'
    import JetButton from '@/../../../Jetstream/Button.vue'
    import JetInput from '@/../../../Jetstream/Input.vue'
    import JetLabel from '@/../../../Jetstream/Label.vue'
    import JetValidationErrors from '@/../../../Jetstream/ValidationErrors.vue'

    export default defineComponent({
        components: {
            Head,
            JetAuthenticationCard,
            JetAuthenticationCardLogo,
            JetButton,
            JetInput,
            JetLabel,
            JetValidationErrors
        },

        props: {
            email: String,
            token: String,
        },

        data() {
            return {
                form: this.$inertia.form({
                    token: this.token,
                    email: this.email,
                    password: '',
                    password_confirmation: '',
                })
            }
        },

        methods: {
            submit() {
                this.form.post(this.route('password.update'), {
                    onFinish: () => this.form.reset('password', 'password_confirmation'),
                })
            }
        }
    })
</script>
