// resources/Jetstream/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue
<template>
    <jet-action-section>
        <template #title>
            Two Factor Authentication
        </template>

        <template #description>
            Add additional security to your account using two factor authentication.
        </template>

        <template #content>
            <h3 class="text-lg font-medium text-gray-900" v-if="twoFactorEnabled">
                You have enabled two factor authentication.
            </h3>

            <h3 class="text-lg font-medium text-gray-900" v-else>
                You have not enabled two factor authentication.
            </h3>

            <div class="mt-3 max-w-xl text-sm text-gray-600">
                <p>
                    When two factor authentication is enabled, you will be prompted for a secure, random token during authentication. You may retrieve this token from your phone's Google Authenticator application.
                </p>
            </div>

            <div v-if="twoFactorEnabled">
                <div v-if="qrCode">
                    <div class="mt-4 max-w-xl text-sm text-gray-600">
                        <p class="font-semibold">
                            Two factor authentication is now enabled. Scan the following QR code using your phone's authenticator application.
                        </p>
                    </div>

                    <div class="mt-4" v-html="qrCode">
                    </div>
                </div>

                <div v-if="recoveryCodes.length > 0">
                    <div class="mt-4 max-w-xl text-sm text-gray-600">
                        <p class="font-semibold">
                            Store these recovery codes in a secure password manager. They can be used to recover access to your account if your two factor authentication device is lost.
                        </p>
                    </div>

                    <div class="grid gap-1 max-w-xl mt-4 px-4 py-4 font-mono text-sm bg-gray-100 rounded-lg">
                        <div v-for="code in recoveryCodes" :key="code">
                            {{ code }}
                        </div>
                    </div>
                </div>
            </div>

            <div class="mt-5">
                <div v-if="! twoFactorEnabled">
                    <jet-confirms-password @confirmed="enableTwoFactorAuthentication">
                        <jet-button type="button" :class="{ 'opacity-25': enabling }" :disabled="enabling">
                            Enable
                        </jet-button>
                    </jet-confirms-password>
                </div>

                <div v-else>
                    <jet-confirms-password @confirmed="regenerateRecoveryCodes">
                        <jet-secondary-button class="mr-3"
                                        v-if="recoveryCodes.length > 0">
                            Regenerate Recovery Codes
                        </jet-secondary-button>
                    </jet-confirms-password>

                    <jet-confirms-password @confirmed="showRecoveryCodes">
                        <jet-secondary-button class="mr-3" v-if="recoveryCodes.length === 0">
                            Show Recovery Codes
                        </jet-secondary-button>
                    </jet-confirms-password>

                    <jet-confirms-password @confirmed="disableTwoFactorAuthentication">
                        <jet-danger-button
                                        :class="{ 'opacity-25': disabling }"
                                        :disabled="disabling">
                            Disable
                        </jet-danger-button>
                    </jet-confirms-password>
                </div>
            </div>
        </template>
    </jet-action-section>
</template>

<script>
    import { defineComponent } from 'vue'
    import JetActionSection from '@/../../../../Jetstream/ActionSection.vue'
    import JetButton from '@/../../../../Jetstream/Button.vue'
    import JetConfirmsPassword from '@/../../../../Jetstream/ConfirmsPassword.vue'
    import JetDangerButton from '@/../../../../Jetstream/DangerButton.vue'
    import JetSecondaryButton from '@/../../../../Jetstream/SecondaryButton.vue'

    export default defineComponent({
        components: {
            JetActionSection,
            JetButton,
            JetConfirmsPassword,
            JetDangerButton,
            JetSecondaryButton,
        },

        data() {
            return {
                enabling: false,
                disabling: false,

                qrCode: null,
                recoveryCodes: [],
            }
        },

        methods: {
            enableTwoFactorAuthentication() {
                this.enabling = true

                this.$inertia.post('/user/two-factor-authentication', {}, {
                    preserveScroll: true,
                    onSuccess: () => Promise.all([
                        this.showQrCode(),
                        this.showRecoveryCodes(),
                    ]),
                    onFinish: () => (this.enabling = false),
                })
            },

            showQrCode() {
                return axios.get('/user/two-factor-qr-code')
                        .then(response => {
                            this.qrCode = response.data.svg
                        })
            },

            showRecoveryCodes() {
                return axios.get('/user/two-factor-recovery-codes')
                        .then(response => {
                            this.recoveryCodes = response.data
                        })
            },

            regenerateRecoveryCodes() {
                axios.post('/user/two-factor-recovery-codes')
                        .then(response => {
                            this.showRecoveryCodes()
                        })
            },

            disableTwoFactorAuthentication() {
                this.disabling = true

                this.$inertia.delete('/user/two-factor-authentication', {
                    preserveScroll: true,
                    onSuccess: () => (this.disabling = false),
                })
            },
        },

        computed: {
            twoFactorEnabled() {
                return ! this.enabling && this.$page.props.user.two_factor_enabled
            }
        }
    })
</script>

// resources/js/Domains/Profile/TwoFactorAuthenticationForm.tsx
import { Inertia } from '@inertiajs/inertia';
import { usePage } from '@inertiajs/inertia-react';
import axios from 'axios';
import clsx from 'clsx';
import React, { useState } from 'react';
import { JetActionSection } from '@/Components/Jetstream/ActionSection';
import { JetButton } from '@/Components/Jetstream/Button';
import { JetConfirmsPassword } from '@/Components/Jetstream/ConfirmsPassword';
import { JetDangerButton } from '@/Components/Jetstream/DangerButton';
import { JetSecondaryButton } from '@/Components/Jetstream/SecondaryButton';

export default function TwoFactorAuthenticationForm() {
  const page = usePage<any>();
  const [enabling, setEnabling] = useState(false);
  const [disabling, setDisabling] = useState(false);
  const [qrCode, setQrCode] = useState<string | null>(null);
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const twoFactorEnabled = page.props?.user?.two_factor_enabled;

  function enableTwoFactorAuthentication() {
    setEnabling(true);

    axios.post('/user/two-factor-authentication').then(() => {
      Promise.all([showQrCode(), showRecoveryCodes()]).then(() => {
        setEnabling(false);
        Inertia.reload();
      });
    });
  }

  function showQrCode() {
    return axios.get('/user/two-factor-qr-code').then(response => {
      setQrCode(response.data.svg);
    });
  }

  function showRecoveryCodes() {
    return axios.get('/user/two-factor-recovery-codes').then(response => {
      setRecoveryCodes(response.data);
    });
  }

  function regenerateRecoveryCodes() {
    axios.post('/user/two-factor-recovery-codes').then(response => {
      showRecoveryCodes();
    });
  }

  function disableTwoFactorAuthentication() {
    setDisabling(true);

    axios.delete('/user/two-factor-authentication').then(() => {
      setDisabling(false);
      Inertia.reload();
    });
  }

  return (
    <JetActionSection
      title={'Two Factor Authentication'}
      description={
        'Add additional security to your account using two factor authentication.'
      }
    >
      {twoFactorEnabled ? (
        <h3 className="text-lg font-medium text-gray-900">
          You have enabled two factor authentication.
        </h3>
      ) : (
        <h3 className="text-lg font-medium text-gray-900">
          You have not enabled two factor authentication.
        </h3>
      )}

      <div className="mt-3 max-w-xl text-sm text-gray-600">
        <p>
          When two factor authentication is enabled, you will be prompted for a
          secure, random token during authentication. You may retrieve this
          token from your phone's Google Authenticator application.
        </p>
      </div>

      {twoFactorEnabled ? (
        <div>
          {qrCode ? (
            <div>
              <div className="mt-4 max-w-xl text-sm text-gray-600">
                <p className="font-semibold">
                  Two factor authentication is now enabled. Scan the following
                  QR code using your phone's authenticator application.
                </p>
              </div>

              <div
                className="mt-4"
                dangerouslySetInnerHTML={{ __html: qrCode || '' }}
              />
            </div>
          ) : null}

          {recoveryCodes.length > 0 ? (
            <div>
              <div className="mt-4 max-w-xl text-sm text-gray-600">
                <p className="font-semibold">
                  Store these recovery codes in a secure password manager. They
                  can be used to recover access to your account if your two
                  factor authentication device is lost.
                </p>
              </div>

              <div className="grid gap-1 max-w-xl mt-4 px-4 py-4 font-mono text-sm bg-gray-100 rounded-lg">
                {recoveryCodes.map(code => (
                  <div key={code}>{code}</div>
                ))}
              </div>
            </div>
          ) : null}
        </div>
      ) : null}

      <div className="mt-5">
        {twoFactorEnabled ? (
          <div>
            {recoveryCodes.length > 0 ? (
              <JetConfirmsPassword onConfirm={regenerateRecoveryCodes}>
                <JetSecondaryButton className="mr-3">
                  Regenerate Recovery Codes
                </JetSecondaryButton>
              </JetConfirmsPassword>
            ) : (
              <JetConfirmsPassword onConfirm={showRecoveryCodes}>
                <JetSecondaryButton className="mr-3">
                  Show Recovery Codes
                </JetSecondaryButton>
              </JetConfirmsPassword>
            )}

            <JetConfirmsPassword onConfirm={disableTwoFactorAuthentication}>
              <JetDangerButton
                className={clsx({ 'opacity-25': disabling })}
                disabled={disabling}
              >
                Disable
              </JetDangerButton>
            </JetConfirmsPassword>
          </div>
        ) : (
          <div>
            <JetConfirmsPassword onConfirm={enableTwoFactorAuthentication}>
              <JetButton
                type="button"
                className={clsx({ 'opacity-25': enabling })}
                disabled={enabling}
              >
                Enable
              </JetButton>
            </JetConfirmsPassword>
          </div>
        )}
      </div>
    </JetActionSection>
  );
}
