// resources/Jetstream/Pages/Teams/Partials/CreateTeamForm.vue
<template>
    <jet-form-section @submitted="createTeam">
        <template #title>
            Team Details
        </template>

        <template #description>
            Create a new team to collaborate with others on projects.
        </template>

        <template #form>
            <div class="col-span-6">
                <jet-label value="Team Owner" />

                <div class="flex items-center mt-2">
                    <img class="object-cover w-12 h-12 rounded-full" :src="$page.props.user.profile_photo_url" :alt="$page.props.user.name">

                    <div class="ml-4 leading-tight">
                        <div>{{ $page.props.user.name }}</div>
                        <div class="text-sm text-gray-700">{{ $page.props.user.email }}</div>
                    </div>
                </div>
            </div>

            <div class="col-span-6 sm:col-span-4">
                <jet-label for="name" value="Team Name" />
                <jet-input id="name" type="text" class="block w-full mt-1" v-model="form.name" autofocus />
                <jet-input-error :message="form.errors.name" class="mt-2" />
            </div>
        </template>

        <template #actions>
            <jet-button :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                Create
            </jet-button>
        </template>
    </jet-form-section>
</template>

<script>
    import { defineComponent } from 'vue'
    import JetButton from '@/../../../../Jetstream/Button.vue'
    import JetFormSection from '@/../../../../Jetstream/FormSection.vue'
    import JetInput from '@/../../../../Jetstream/Input.vue'
    import JetInputError from '@/../../../../Jetstream/InputError.vue'
    import JetLabel from '@/../../../../Jetstream/Label.vue'

    export default defineComponent({
        components: {
            JetButton,
            JetFormSection,
            JetInput,
            JetInputError,
            JetLabel,
        },

        data() {
            return {
                form: this.$inertia.form({
                    name: '',
                })
            }
        },

        methods: {
            createTeam() {
                this.form.post(route('teams.store'), {
                    errorBag: 'createTeam',
                    preserveScroll: true
                });
            },
        },
    })
</script>

// resources/js/Pages/Teams/Partials/CreateTeamForm.tsx
import * as React from 'react';
import { JetActionMessage, JetButton, JetFormSection, JetInput, JetLabel } from '@/Components/Jetstream';
import { useForm } from '@inertiajs/inertia-react';
import { User } from '@/types';
import { JetInputError } from '@/Components/Jetstream/InputError';
import clsx from 'clsx';
import useRoute from '@/Hooks/useRoute';

type Props = {
  user: User;
};

export const CreateTeamForm = ({ user }: Props) => {
  const route = useRoute();
  const form = useForm({
    name: '',
  });

  const createTeam = () => {
    form.post(route('teams.store'), {
      errorBag: 'createTeam',
      preserveScroll: true,
    });
  };

  return (
    <JetFormSection
      title="Team Details"
      description="Create a new team to collaborate with others on projects."
      onSubmit={createTeam}
      renderActions={() => (
        <>
          <JetButton
            className={clsx({ 'opacity-25': form.processing })}
            disabled={form.processing}
          >
            Create
          </JetButton>
          <JetActionMessage on={form.recentlySuccessful} className="ml-3">
            Created.
          </JetActionMessage>
        </>
      )}
    >
      <div className="col-span-6 sm:col-span-4">
        <JetLabel value="Team Owner" />
        <div className="flex items-center mt-2">
          <img className="w-12 h-12 rounded-full object-cover" src={user.profile_photo_url} alt={user.name} />
          <div className="ml-4 leading-tight">
            <div>{user.name}</div>
            <div className="text-gray-700 text-sm">{user.email}</div>
          </div>
        </div>
      </div>
      <div className="col-span-6 sm:col-span-4">
        <JetLabel htmlFor="name" value="Team Name" />
        <JetInput
          id="name"
          type="text"
          className="mt-1 block w-full"
          value={form.data.name}
          onChange={e => form.setData('name', e.currentTarget.value)}
        />
        <JetInputError message={form.errors.name} className="mt-2" />
      </div>
    </JetFormSection>
  );
};
