// resources/js/Domains/Profile/DeleteUserForm.tsx
import { useForm } from '@inertiajs/inertia-react';
import clsx from 'clsx';
import React, { useRef, useState } from 'react';
import useRoute from '@/Hooks/useRoute';
import { JetActionSection } from '@/Components/Jetstream/ActionSection';
import { JetDangerButton } from '@/Components/Jetstream/DangerButton';
import { JetDialogModal } from '@/Components/Jetstream/DialogModal';
import { JetInput } from '@/Components/Jetstream/Input';
import { JetInputError } from '@/Components/Jetstream/InputError';
import { JetSecondaryButton } from '@/Components/Jetstream/SecondaryButton';

export default function DeleteUserForm() {
  const route = useRoute();
  const [confirmingUserDeletion, setConfirmingUserDeletion] = useState(false);
  const form = useForm({
    password: '',
  });
  const passwordRef = useRef<HTMLInputElement>(null);

  function confirmUserDeletion() {
    setConfirmingUserDeletion(true);

    setTimeout(() => passwordRef.current?.focus(), 250);
  }

  function closeModal() {
    setConfirmingUserDeletion(false);
    form.reset();
  }

  function deleteUser() {
    form.delete(route('current-user.destroy'), {
      preserveScroll: true,
      onSuccess: () => closeModal(),
      onError: () => passwordRef.current?.focus(),
      onFinish: () => form.reset(),
    });
  }

  return (
    <JetActionSection
      title="Delete Account"
      description="Permanently delete your account."
    >
      <div className="max-w-xl text-sm text-gray-600">
        Once your account is deleted, all of its resources and data will be
        permanently deleted. Before deleting your account, please download any
        data or information that you wish to retain.
      </div>

      <div className="mt-5">
        <JetDangerButton onClick={confirmUserDeletion}>
          Delete Account
        </JetDangerButton>
      </div>

      {/* <!-- Delete Account Confirmation Modal --> */}
      <JetDialogModal isOpen={confirmingUserDeletion} onClose={closeModal}>
        <JetDialogModal.Content title="Delete Account">
          Are you sure you want to delete your account? Once your account is
          deleted, all of its resources and data will be permanently deleted.
          Please enter your password to confirm you would like to permanently
          delete your account.
          <div className="mt-4">
            <JetInput
              type="password"
              className="mt-1 block w-3/4"
              placeholder="Password"
              value={form.data.password}
              onChange={e => form.setData('password', e.currentTarget.value)}
            />

            <JetInputError message={form.errors.password} className="mt-2" />
          </div>
        </JetDialogModal.Content>
        <JetDialogModal.Footer>
          <JetSecondaryButton onClick={closeModal}>Cancel</JetSecondaryButton>

          <JetDangerButton
            onClick={deleteUser}
            className={clsx('ml-2', { 'opacity-25': form.processing })}
            disabled={form.processing}
          >
            Delete Account
          </JetDangerButton>
        </JetDialogModal.Footer>
      </JetDialogModal>
    </JetActionSection>
  );
}

// resources/Jetstream/Pages/Profile/Partials/DeleteUserForm.vue
<template>
    <jet-action-section>
        <template #title>
            Delete Account
        </template>

        <template #description>
            Permanently delete your account.
        </template>

        <template #content>
            <div class="max-w-xl text-sm text-gray-600">
                Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.
            </div>

            <div class="mt-5">
                <jet-danger-button @click="confirmUserDeletion">
                    Delete Account
                </jet-danger-button>
            </div>

            <!-- Delete Account Confirmation Modal -->
            <jet-dialog-modal :show="confirmingUserDeletion" @close="closeModal">
                <template #title>
                    Delete Account
                </template>

                <template #content>
                    Are you sure you want to delete your account? Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.

                    <div class="mt-4">
                        <jet-input type="password" class="mt-1 block w-3/4" placeholder="Password"
                                    ref="password"
                                    v-model="form.password"
                                    @keyup.enter="deleteUser" />

                        <jet-input-error :message="form.errors.password" class="mt-2" />
                    </div>
                </template>

                <template #footer>
                    <jet-secondary-button @click="closeModal">
                        Cancel
                    </jet-secondary-button>

                    <jet-danger-button class="ml-2" @click="deleteUser" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                        Delete Account
                    </jet-danger-button>
                </template>
            </jet-dialog-modal>
        </template>
    </jet-action-section>
</template>

<script>
    import { defineComponent } from 'vue'
    import JetActionSection from '@/../../../../Jetstream/ActionSection.vue'
    import JetDialogModal from '@/../../../../Jetstream/DialogModal.vue'
    import JetDangerButton from '@/../../../../Jetstream/DangerButton.vue'
    import JetInput from '@/../../../../Jetstream/Input.vue'
    import JetInputError from '@/../../../../Jetstream/InputError.vue'
    import JetSecondaryButton from '@/../../../../Jetstream/SecondaryButton.vue'

    export default defineComponent({
        components: {
            JetActionSection,
            JetDangerButton,
            JetDialogModal,
            JetInput,
            JetInputError,
            JetSecondaryButton,
        },

        data() {
            return {
                confirmingUserDeletion: false,

                form: this.$inertia.form({
                    password: '',
                })
            }
        },

        methods: {
            confirmUserDeletion() {
                this.confirmingUserDeletion = true;

                setTimeout(() => this.$refs.password.focus(), 250)
            },

            deleteUser() {
                this.form.delete(route('current-user.destroy'), {
                    preserveScroll: true,
                    onSuccess: () => this.closeModal(),
                    onError: () => this.$refs.password.focus(),
                    onFinish: () => this.form.reset(),
                })
            },

            closeModal() {
                this.confirmingUserDeletion = false

                this.form.reset()
            },
        },
    })
</script>
