// resources/Jetstream/Pages/PrivacyPolicy.vue
<template>
    <Head title="Privacy Policy" />

    <div class="font-sans text-gray-900 antialiased">
        <div class="pt-4 bg-gray-100">
            <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
                <div>
                    <jet-authentication-card-logo />
                </div>

                <div v-html="policy" class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import { defineComponent } from 'vue'
import { Head } from '@inertiajs/inertia-vue3';
import JetAuthenticationCardLogo from '@/../../Jetstream/AuthenticationCardLogo.vue'

export default defineComponent({
    props: ['policy'],

    components: {
        Head,
        JetAuthenticationCardLogo,
    },
})
</script>

// resources/js/Pages/PrivacyPolicy.tsx
import React from 'react';
import { JetAuthenticationCardLogo } from '@/Components/Jetstream/AuthenticationCardLogo';
import { Head } from '@inertiajs/inertia-react';

interface Props {
  policy: string;
}

export default function PrivacyPolicy({ policy }: Props) {
  return (
    <div>
      <Head title="Privacy Policy" />
      <div className="font-sans text-gray-900 antialiased">
        <div className="pt-4 bg-gray-100">
          <div className="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
              <JetAuthenticationCardLogo />
            </div>

            <div
              className="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose"
              dangerouslySetInnerHTML={{ __html: policy }}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
