// resources/Jetstream/Pages/Teams/Show.vue
<template>
    <app-layout title="Team Settings">
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                Team Settings
            </h2>
        </template>

        <div>
            <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
                <update-team-name-form :team="team" :permissions="permissions" />

                <team-member-manager class="mt-10 sm:mt-0"
                            :team="team"
                            :available-roles="availableRoles"
                            :user-permissions="permissions" />

                <template v-if="permissions.canDeleteTeam && ! team.personal_team">
                    <jet-section-border />

                    <delete-team-form class="mt-10 sm:mt-0" :team="team" />
                </template>
            </div>
        </div>
    </app-layout>
</template>

<script>
    import { defineComponent } from 'vue'
    import AppLayout from '@/Layouts/AppLayout.vue'
    import DeleteTeamForm from '@/Pages/Teams/Partials/DeleteTeamForm.vue'
    import JetSectionBorder from '@/../../../Jetstream/SectionBorder.vue'
    import AddTeamMember from '@/Pages/Teams/Partials/TeamMemberManager.vue'
    import UpdateTeamNameForm from '@/Pages/Teams/Partials/UpdateTeamNameForm.vue'

    export default defineComponent({
        props: [
            'team',
            'availableRoles',
            'permissions',
        ],

        components: {
            AppLayout,
            DeleteTeamForm,
            JetSectionBorder,
            TeamMemberManager,
            UpdateTeamNameForm,
        },
    })
</script>

// resources/js/Pages/Teams/Show.tsx
import * as React from 'react';
import { AppLayout } from '@/Layouts/AppLayout';
import { UpdateTeamNameForm } from '@/Pages/Teams/Partials/UpdateTeamNameForm';
import { JetstreamTeamPermissions, Role, Team } from '@/types';
import { AddTeamMember } from '@/Pages/Teams/Partials/AddTeamMember';
import { JetSectionBorder } from '@/Components/Jetstream';
import { ManageTeamMembers } from '@/Pages/Teams/Partials/ManageTeamMembers';
import { PendingTeamInvitation } from '@/Pages/Teams/Partials/PendingTeamInvitation';

interface Props {
  team: Team;
  permissions: JetstreamTeamPermissions;
  availableRoles: Role[];
}

const Show = ({ availableRoles, team, permissions }: Props) => {
  return (
    <AppLayout title="Team Settings">
      <div className="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8 bg-gray-100">
        <UpdateTeamNameForm team={team} permissions={permissions} />
        {permissions.canAddTeamMembers && (
          <>
            <JetSectionBorder />
            <AddTeamMember
              team={team}
              availableRoles={availableRoles}
              permissions={permissions}
            />
            {team.team_invitations.length > 0 && (
              <>
                <JetSectionBorder />
                <PendingTeamInvitation team={team} permissions={permissions} />
              </>
            )}
            <JetSectionBorder />
            <ManageTeamMembers
              team={team}
              availableRoles={availableRoles}
              permissions={permissions}
            />
          </>
        )}
      </div>
    </AppLayout>
  );
};

export default Show;
