// resources/Jetstream/Pages/ForgotPassword.vue
<template>
    <Head title="Forgot Password" />

    <jet-authentication-card>
        <template #logo>
            <jet-authentication-card-logo />
        </template>

        <div class="mb-4 text-sm text-gray-600">
            Forgot your password? No problem. Just let us know your email address and we will email you a password reset link that will allow you to choose a new one.
        </div>

        <div v-if="status" class="mb-4 font-medium text-sm text-green-600">
            {{ status }}
        </div>

        <jet-validation-errors class="mb-4" />

        <form @submit.prevent="submit">
            <div>
                <jet-label for="email" value="Email" />
                <jet-input id="email" type="email" class="mt-1 block w-full" v-model="form.email" required autofocus />
            </div>

            <div class="flex items-center justify-end mt-4">
                <jet-button :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Email Password Reset Link
                </jet-button>
            </div>
        </form>
    </jet-authentication-card>
</template>

<script>
    import { defineComponent } from 'vue'
    import { Head } from '@inertiajs/inertia-vue3';
    import JetAuthenticationCard from '@/../../../Jetstream/AuthenticationCard.vue'
    import JetAuthenticationCardLogo from '@/../../../Jetstream/AuthenticationCardLogo.vue'
    import JetButton from '@/../../../Jetstream/Button.vue'
    import JetInput from '@/../../../Jetstream/Input.vue'
    import JetLabel from '@/../../../Jetstream/Label.vue'
    import JetValidationErrors from '@/../../../Jetstream/ValidationErrors.vue'

    export default defineComponent({
        components: {
            Head,
            JetAuthenticationCard,
            JetAuthenticationCardLogo,
            JetButton,
            JetInput,
            JetLabel,
            JetValidationErrors
        },

        props: {
            status: String
        },

        data() {
            return {
                form: this.$inertia.form({
                    email: ''
                })
            }
        },

        methods: {
            submit() {
                this.form.post(this.route('password.email'))
            }
        }
    })
</script>

// resources/js/Pages/Auth/ForgotPassword.tsx
import * as React from 'react';
import { FormEvent } from 'react';
import { Head, useForm } from '@inertiajs/inertia-react';

import useRoute from '@/Hooks/useRoute';
import { GuestLayout } from '@/Layouts/GuestLayout';
import { JetButton } from '@/Components/Jetstream/Button';
import { AuthLabel } from '@/Components/Auth/Label';
import { AuthInput } from '@/Components/Auth/Input';
import { JetBanner } from '@/Components/Jetstream';

interface Props {
  status: string;
}

export default function ForgotPassword({ status }: Props) {
  const route = useRoute();
  const form = useForm({
    email: '',
  });

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    form.post(route('password.email'));
  }

  return (
    <GuestLayout>
      <Head title="Forgot Password" />

      {status && <JetBanner className="mb-4 rounded-md" message={status} style="success" />}

      <div className="mb-4 text-sm text-gray-600">
        Forgot your password? No worries! Let us know your email address
        and we will email you a password reset link that will allow you to
        choose a new one.
      </div>

      <form onSubmit={onSubmit}>
        <div>
          <AuthLabel title="Email" name="Email" error={form.errors.email} />
          <AuthInput
            id="email"
            type="email"
            className="mt-1 block w-full"
            value={form.data.email}
            onChange={e => form.setData('email', e.currentTarget.value)}
            required
            autoFocus
            hasError={!!form.errors.email}
          />
        </div>

        <div className="flex items-center justify-end mt-4">
          <JetButton processing={form.processing}>
            Email Password Reset Link
          </JetButton>
        </div>
      </form>
    </GuestLayout>
  );
}
